### ISSUE TITLE
Bug : configuration - entity - relationshipNaming : Preserve don't work

### ISSUE THREAD

**Issue by capslock66** [loresoft/EntityFrameworkCore.Generator#21] opened 2019-05-17 04:23 UTC
entity:
    relationshipNaming: Preserve

When I set to Suffix, he "List" is well appended
When I set to Plural or don't set relationshipNaming , result is Pluralized (default)
But When I set the relationshipNaming to Preserve, result is  "singularized"
previous relationShip name is not used.

**Comment by pwelter34** [comment] 2019-05-18 14:29
thanks for opening issue, this is a duplicate of #10

**Closed by pwelter34** 2019-05-18 14:29 UTC
Labels: duplicate

**Comment by capslock66** [comment] 2019-05-18 15:49
Not really a duplicate of #10 :
   entityNaming: Preserve
   propertyNaming: Preserve
here is on 
   relationshipNaming: Preserve
